apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ndwu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wnid-tenant/rhtap-demo-app/hacbs-test-project-ndwu@sha256:9d680c5f308c96310e697310c17c6e7a85d55530783aeb2a2e7623c65708dd0d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
