apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ndwu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ndwu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ndwu
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ndwu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ndwu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wnid-tenant/rhtap-demo-app/hacbs-test-project-ndwu@sha256:9d680c5f308c96310e697310c17c6e7a85d55530783aeb2a2e7623c65708dd0d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
